BestTourPlan/Models/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace BestTourPlan.Models
{
    public class LoginViewModel
    {
        [Required]
        [Display(Name = "Login")]
        public string UserName { get; set; }
        [Required]
        [UIHint("password")]
        [Display(Name = "Password")]
        public string Password { get; set; }
    }
}

BestTourPlan/Areas/Admin/Controllers/HomeController.cs
using BestTourPlan.Domain;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BestTourPlan.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class HomeController : Controller
    {
        private readonly DataHelper dataHelper;

        public HomeController(DataHelper dataHelper)
        {
            this.dataHelper = dataHelper;
        }

        public IActionResult Index()
        {
            return View(dataHelper.Hotels.GetHotels());
        }
    }
}

BestTourPlan/Controllers/AccountController.cs
using BestTourPlan.Domain;
using BestTourPlan.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BestTourPlan.Controllers
{
    [Authorize]
    public class AccountController : Controller
    {
        private readonly UserManager<CustomIdentityUser> userManager;
        private readonly SignInManager<CustomIdentityUser> signInManager;
        public AccountController(
            UserManager<CustomIdentityUser> userManager, 
            SignInManager<CustomIdentityUser> signInManager)
        {
            this.userManager = userManager;
            this.signInManager = signInManager;
        }

        [AllowAnonymous]
        public IActionResult Login(string returnUrl)
        {
            ViewBag.returnUrl = returnUrl;
            return View(new LoginViewModel());
        }
        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> Login(LoginViewModel model, string returnUrl)
        {
            if (ModelState.IsValid)
            {
                var user = await userManager.FindByNameAsync(model.UserName);
                if (user != null)
                {
                    await signInManager.SignOutAsync();
                    Microsoft.AspNetCore.Identity.SignInResult result = 
                        await signInManager.PasswordSignInAsync(user, model.Password, false, false);
                    if (result.Succeeded)
                    {
                        return Redirect(returnUrl ?? "/");
                    }
                }
                ModelState.AddModelError(nameof(LoginViewModel.UserName), "Wrong login or password");
            }
            return View(model);
        }

        [Authorize]
        public async Task<IActionResult> Logout()
        {
            await signInManager.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }
    }
}

BestTourPlan/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace BestTourPlan.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

BestTourPlan/Controllers/HotelController.cs
using BestTourPlan.Domain;
using Microsoft.AspNetCore.Mvc;
using System;

namespace BestTourPlan.Controllers
{
    public class HotelController : Controller
    {
        private readonly DataHelper dataHelper;

        public HotelController(DataHelper dataHelper)
        {
            this.dataHelper = dataHelper;
        }

        public IActionResult Index(Guid id)
        {
            return View(dataHelper.Hotels.GetHotelById(id));
        }
    }
}

BestTourPlan/Areas/Admin/Views/Home/Index.cshtml
@model IQueryable<Hotel>
@{
    string strTitle = "Admin panel";
    ViewBag.Title = strTitle;
}

<div>
    <h2>@strTitle</h2>
    <div>
        <h3>Hotels</h3>
        <div class="div-box">
            <a asp-area="Admin" asp-controller="Hotel" asp-action="Edit" asp-route-id="">Add hotel</a>
        </div>
        @if (Model.Any())
        {
            <div>
                @foreach (Hotel entity in Model)
                {
                    <div>
                        <a asp-area="Admin" asp-controller="Hotel" asp-action="Edit" asp-route-id="@entity.Id">edit</a>
                        <form 
                              id="form-@entity.Id" 
                              asp-area="Admin" 
                              asp-controller="Hotel" asp-action="Delete" method="post">
                            <input type="hidden" name="id" value="@entity.Id">
                            @*<a href="#" onclick="document.getElementById('form-@entity.Id').submit();">delete</a>*@
                        </form>
                        <a asp-area="" asp-controller="Hotel" asp-action="Index" asp-route-id="@entity.Id">
                            @($"{entity.Name}")
                        </a>
                    </div>
                }
            </div>
        }
    </div>
    @*<div>
        <h3>Edit pages</h3>
        <a asp-area="Admin" asp-controller="Hotels" asp-action="Edit">Hotels</a>
        <a asp-area="Admin" asp-controller="Activities" asp-action="Edit">Activities</a>
        <a asp-area="Admin" asp-controller="Reviews" asp-action="Edit">Reviews</a>
    </div>*@
    <div>
        <form asp-area="" asp-controller="Account" asp-action="Logout" method="post">
            <input type="submit" value="Log out" />
        </form>
    </div>
</div>

BestTourPlan/Views/Home/Index.cshtml
@model IQueryable<BestTourPlan.Domain.Entities.Hotel>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section class="hotels">
    <div class="container">
        <h2 class="hotels__title">
            Hotels
        </h2>
        
        <div class="hotels-wrapper">
            @foreach (var item in Model)
            {
                <div class="card hotels__card">
                    <img src=@Url.Content(item.ImagePath)
                         alt="Image: @Html.DisplayFor(modelItem => item.Name)"
                         class="card__image">
                    <h3 class="card__title">@Html.DisplayFor(modelItem => item.Name)</h3>
                    <div class="hotels__stars">
                        @for (int i = 0; i < (int)item.Rating; i++)
                        {
                            <img class="star" src="~/img/star.svg" alt="star">
                        }
                    </div>
                    <a asp-area=""
                       asp-controller="Hotel"
                       asp-action="Index"
                       asp-route-id="@item.Id"
                       class="hotels__button">Details</a>
                </div>
            }
        </div>
    </div>
</section>

BestTourPlan/Views/Hotel/Index.cshtml
@await Html.PartialAsync("BreadcrumbPartial")
@await Html.PartialAsync("HotelPartial")
@await Html.PartialAsync("ModalPartial")

BestTourPlan/Views/Shared/ActivitiesPartial.cshtml
<section class="activities">
    <div class="container">
        <h2 class="activities__title"
            data-aos="fade-right"
            data-aos-duration="700"
            data-aos-easing="ease-in-sine">
            Other Activities
        </h2>
        <div class="activities-wrapper">
            <div class="card activities__card" data-aos="fade-up" data-aos-delay="100">
                <img src="~/img/activities/1.jpg"
                     alt="Image: The curious corner of chamarel"
                     class="card__image">
                <h3 class="card__title">The curious corner of&nbsp;chamarel</h3>
                <button class="card__button"
                        data-toggle="modal"
                        data-href="#booking-modal">
                    Book Now
                </button>
            </div>
            <div class="card activities__card" data-aos="fade-up" data-aos-delay="200">
                <img src="~/img/activities/2.jpg"
                     alt="Image: Gymkhana club golf course"
                     class="card__image">
                <h3 class="card__title">Gymkhana club golf course</h3>
                <button class="card__button"
                        data-toggle="modal"
                        data-href="#booking-modal">
                    Book Now
                </button>
            </div>
            <div class="card activities__card" data-aos="fade-up" data-aos-delay="300">
                <img src="~/img/activities/3.jpg"
                     alt="Image: Tamarind falls hiking trip - full Day"
                     class="card__image">
                <h3 class="card__title">Tamarind falls hiking<br />trip - full day</h3>
                <button class="card__button"
                        data-toggle="modal"
                        data-href="#booking-modal">
                    Book Now
                </button>
            </div>
            <div class="card activities__card" data-aos="fade-up" data-aos-delay="400">
                <img src="~/img/activities/4.jpg"
                     alt="Image: The blue marine discovery quest"
                     class="card__image">
                <h3 class="card__title">The blue marine discovery quest</h3>
                <button class="card__button"
                        data-toggle="modal"
                        data-href="#booking-modal">
                    Book Now
                </button>
            </div>
        </div>
    </div>
</section>

BestTourPlan/Views/Shared/BreadcrumbPartial.cshtml
<nav class="breadcrumb">
    <div class="container">
        <ul class="breadcrumb-list">
            <li class="breadcrumb-list__item">
                <a href="#" class="breadcrumb-list__link">Home</a>
            </li>
            <li class="breadcrumb-list__item">
                <a href="#" class="breadcrumb-list__link">Flash Offers</a>
            </li>
            <li class="breadcrumb-list__item">
                Grand Hilton Hotel
            </li>
        </ul>
    </div>
</nav>

BestTourPlan/Views/Shared/FooterPartial.cshtml
@using BestTourPlan.Services
<footer class="footer">
    <div class="container footer__container">
        <div class="footer-wrapper">
            <a href="#"
               class="logo footer__logo">
                <img src="~/img/vertical-logo.svg"
                     alt="Image: Best Tour Plan">
            </a>
            <div class="footer__list footer__categories">
                <h3 class="footer__title">ALL CATEGORIES</h3>
                <ul class="footer__ul">
                    <li class="footer__item">
                        <a href="#" class="footer__link">All Deals</a>
                    </li>
                    <li class="footer__item">
                        <a 
                           asp-area=""
                           asp-controller="Home"
                           asp-action="Index" 
                           class="footer__link">Hotels</a>
                    </li>
                    <li class="footer__item">
                        <a href="#" class="footer__link">Activities</a>
                    </li>
                    <li class="footer__item">
                        <a href="#" class="footer__link">Spa Packages</a>
                    </li>
                    <li class="footer__item">
                        <a href="#" class="footer__link">Hotel Day Packages</a>
                    </li>
                    <li class="footer__item">
                        <a href="#" class="footer__link">Restaurants</a>
                    </li>
                    <li class="footer__item">
                        <a href="#" class="footer__link">Fitness</a>
                    </li>
                    <li class="footer__item">
                        <a href="#" class="footer__link">Rodrigues</a>
                    </li>
                </ul>
            </div>
            <div class="footer__list footer__additional">
                <h3 class="footer__title">ADDITIONAL INFORMATION</h3>
                <ul class="footer__ul">
                    <li class="footer__item">
                        <a href="#" class="footer__link">About Us</a>
                    </li>
                    <li class="footer__item">
                        <a href="#" class="footer__link">Contact Us</a>
                    </li>
                    <li class="footer__item">
                        <a href="#" class="footer__link">How does it work?</a>
                    </li>
                    <li class="footer__item">
                        <a href="#" class="footer__link">Frequently Asked Questions</a>
                    </li>
                    <li class="footer__item">
                        <a href="#" class="footer__link">Deals.mu loyalty program</a>
                    </li>
                    <li class="footer__item">
                        <a href="#" class="footer__link">Promote your Business on BTP</a>
                    </li>
                </ul>
            </div>
            <div class="footer__social-network">
                <h3 class="footer__title footer__title--inline">Social Network</h3>
                <div class="footer__social-links">
                    <a href="https://www.facebook.com/" class="footer__link">
                        <img src="~/img/fb.svg" alt="Icon: facebook">
                    </a>
                    <a href="https://www.youtube.com/" class="footer__link">
                        <img src="~/img/yt.svg" alt="Icon: youtube">
                    </a>
                    <a href="https://www.instagram.com/" class="footer__link">
                        <img src="~/img/inst.svg" alt="Icon: instagram">
                    </a>
                </div>
            </div>
            <div class="footer__list footer__legal">
                <h3 class="footer__title">LEGAL INFORMATION</h3>
                <ul class="footer__ul">
                    <li class="footer__item">
                        <a href="#" class="footer__link">Terms & Conditions</a>
                    </li>
                    <li class="footer__item">
                        <a href="#" class="footer__link">Disclaimer</a>
                    </li>
                    <li class="footer__item">
                        <a href="#" class="footer__link">Cancellation policy</a>
                    </li>
                    <li class="footer__item">
                        <a href="#" class="footer__link">Privacy</a>
                    </li>
                </ul>
            </div>
            <div class="footer__contact-details">
                <h3 class="footer__title footer__title--mb-3">Contact Details</h3>
                <p class="footer__text">Feel free to contact us by phone, email or by our contact form</p>
                <ul class="footer__ul footer__ul--details">
                    <li class="footer__item footer__item--mb-2">
                        <div class="footer__icon-wrapper">
                            <img src="~/img/contacts/address.svg"
                                 alt="Image: address"
                                 class="footer__icon">
                        </div>
                        <span>9748 Blossom Hill Rd undefined Lansing, Idaho 68545 United States</span>
                    </li>
                    <li class="footer__item footer__item--mb-2">
                        <div class="footer__icon-wrapper">
                            <img src="~/img/contacts/phone.svg"
                                 alt="Image: phone"
                                 class="footer__icon">
                        </div>
                        <div class="footer__phones">
                            <p class="footer__phone">
                                Tel (business hours) :
                                <a href="tel:269-15-00" class="footer__link"> <nobr>269-15-00</nobr></a>
                            </p>
                            <p class="footer__phone">
                                Tel (hotline) Monday - Saturday:
                                <a href="tel:52-56-61-38" class="footer__link"><nobr>52-56-61-38</nobr></a>
                                (08:00 am – 20:00 pm)
                            </p>
                            <p class="footer__phone">
                                Tel (hotline) Sunday:
                                <a href="tel:52-56-61-38" class="footer__link">
                                    <nobr>52-56-61-38</nobr>
                                </a>
                                (08:00 am – 14:00 pm)
                            </p>
                        </div>
                    </li>
                    <li class="footer__item footer__item--mb-2">
                        <div class="footer__icon-wrapper">
                            <img src="~/img/contacts/mail.svg"
                                 alt="Image: mail"
                                 class="footer__icon">
                        </div>
                        <a href="mailto:@Configuration.ContactEmail"
                           class="footer__link">@Configuration.ContactEmail</a>
                    </li>
                </ul>
            </div>
            <div class="footer__contact-form">
                <h3 class="footer__title footer__title--form">Send us a message</h3>
                <form action="send.php"
                      class="footer__form form"
                      method="POST">
                    <div class="footer__input-group">
                        <input type="text"
                               class="input footer__input"
                               placeholder="Your Full Name"
                               name="name"
                               required
                               minlength="2">
                    </div>
                    <div class="footer__input-group">
                        <input type="tel"
                               class="input footer__input"
                               placeholder="Phone Number"
                               name="phone"
                               required
                               data-mask="+7(000)-000-00-00">
                    </div>
                    <textarea class="message footer__message"
                              placeholder="Message"
                              name="message"></textarea>
                    <span class="footer__info--top">*&nbsp;Required fields</span>
                    <button type="submit" class="button footer__button">Send</button>
                    <span class="footer__info--span">*&nbsp;Required fields</span>
                </form>
            </div>
        </div>
        <div class="footer-bottom">
            <div class="footer__conditions">
                <span>Disclaimer&nbsp;&nbsp;</span>
                <span>Conditions of use&nbsp;</span>
                <span>Cancellation&nbsp;policy</span>
            </div>
            <div class="footer__payment">
                <img src="~/img/payment.svg"
                     alt="Icon: payment cards"
                     class="footer__cards">
            </div>
        </div>
    </div>
</footer>

BestTourPlan/Views/Shared/HeaderPartial.cshtml
<header class="navbar navbar__mobile--fixed">
    <div class="container">
        <div class="navbar-top">
            <a href="#" class="logo">
                <img src="~/img/horizontal-logo.svg"
                     alt="Logo: Best Tour Plan"
                     class="logo__image">
            </a>

            <form action="#" class="search navbar__search navbar__search--mobile--hidden">
                <input type="text"
                       class="input search__input"
                       placeholder="Search Location" />
                <button class="search__button">
                    <img src="~/img/search.svg"
                         alt="Button: Search">
                </button>
            </form>

            <a href="#" class="user navbar__user navbar__user--mobile--hidden">
                <img src="~/img/admin.png"
                     alt="Avatar: Admin"
                     class="user__avatar">
                <span class="user__name">Admin</span>
            </a>
            <button class="menu-button navbar-top__menu-button">
                <span class="menu-button__line"></span>
                <span class="menu-button__line"></span>
                <span class="menu-button__line"></span>
            </button>
        </div>
    </div>
    <nav class="navbar-bottom">
        <div class="container">
            <ul class="navbar-menu">
                <li class="navbar-menu__item navbar-menu__item--mobile--visible">
                    <a href="#" class="user navbar__user navbar__user--mobile--visible">
                        <img src="~/img/admin.png"
                             alt="Avatar: Admin"
                             class="user__avatar">
                        <span class="user__name user__name--light">Admin</span> <!--Here there will be user's photo-->
                    </a>
                </li>
                <li class="navbar-menu__item navbar-menu__item--mobile--visible">
                    <form action="#" class="search navbar__search navbar__search--mobile--visible">
                        <input type="text"
                               class="search__input search__input--mobile--visible"
                               placeholder="Search Location" />
                        <button class="search__button search__button--mobile--visible">
                            <img src="~/img/search.svg"
                                 alt="Button: Search">
                        </button>
                    </form>
                </li>
                <li class="navbar-menu__item">
                    <a href="#" class="navbar-menu__link">All Deals</a>
                </li>
                <li class="navbar-menu__item">
                    <a 
                       asp-area=""
                       asp-controller="Home"
                       asp-action="Index"
                       class="navbar-menu__link">Hotels</a>
                </li>
                <li class="navbar-menu__item">
                    <a href="#" class="navbar-menu__link">Activities</a>
                </li>
                <li class="navbar-menu__item">
                    <a href="#" class="navbar-menu__link">Hotel Day Packages</a>
                </li>
                <li class="navbar-menu__item">
                    <a href="#" class="navbar-menu__link">Restaurants</a>
                </li>
                <li class="navbar-menu__item">
                    <a href="#" class="navbar-menu__link">Events</a>
                </li>
                <li class="navbar-menu__item">
                    <a href="#" class="navbar-menu__link">Rodrigues</a>
                </li>
            </ul>
        </div>
    </nav>
</header>

BestTourPlan/Views/Shared/HotelPartial.cshtml
@model BestTourPlan.Domain.Entities.Hotel

@using BestTourPlan.Utility

<section class="hotel">
    <div class="container">
        <div class="hotel-info">
            <div class="hotel-info__text">
                <div class="hotel-wrapper">
                    @for (int i = 0; i < Constants.MaxRating; i++)
                    {
                        <img class="star" src="~/img/star.svg" alt="star">
                    }
                    <h1 class="hotel-name hotel-info__name">@Model.Name</h1>
                    <span class="offer hotel-info__offer">Flash Offer</span>
                </div>
                <p class="hotel-description hotel-info__description">
                    @Model.Description
                </p>
            </div>
            <div class="rating hotel-info__rating"
                 data-toggle="modal"
                 data-href="#rating-modal">
                <span class="rating__text">User Ratings</span>
                <span class="rating__counter">@Model.Rating/</span>
                <!--
                -->
                <span class="rating__max">@Constants.MaxRating</span>
            </div>
        </div>
        <div class="hotel-grid">
            <div class="swiper-container hotel-slider hotel__slider">
                <!--Images will be chosen by admin-->
                <div class="swiper-wrapper">
                    <div class="swiper-slide hotel-slider__item">
                        <img src="~/img/slide-1.jpg" alt="Slide 1" class="hotel-slider__image">
                    </div>
                    <div class="swiper-slide hotel-slider__item">
                        <img src="~/img/slide-2.jpg" alt="Slide 2" class="hotel-slider__image">
                    </div>
                    <div class="swiper-slide hotel-slider__item">
                        <img src="~/img/slide-3.jpg" alt="Slide 3" class="hotel-slider__image">
                    </div>
                    <div class="swiper-slide hotel-slider__item">
                        <img src="~/img/slide-4.jpg" alt="Slide 4" class="hotel-slider__image">
                    </div>
                </div>

                <button class="hotel-slider__button hotel-slider__button--prev"></button>
                <button class="hotel-slider__button hotel-slider__button--next"></button>
            </div>
            <div class="hotel-right">
                <div class="booking">
                    <div class="booking__info">
                        <div class="booking__price">
                            <span class="booking__start">price starts as</span>
                            <strong class="booking__pricetag">$ @Model.Price</strong>
                            <span class="booking__per-room">per room / night</span>
                        </div>
                        <div class="booking__room">
                            <div class="booking__text">
                                <img src="~/img/user.svg"
                                     alt="Icon: user"
                                     class="booking__icon">
                                <span class="booking__descripion">2 x Guests</span>
                            </div>
                            <div class="booking__text">
                                <img src="~/img/room.svg"
                                     alt="Icon: room"
                                     class="booking__icon">
                                <span class="booking__descripion">1 x Room</span>
                            </div>
                        </div>
                    </div>
                    <div class="booking__call-center">
                        <span class="booking__heading">Quick Booking</span>
                        <a href="tel:12100" class="booking__phone">
                            <img src="~/img/phone-call.svg" alt="Icon: phone">
                            <span class="booking__number">12100</span>
                        </a>
                    </div>
                    <button data-toggle="modal"
                            data-href="#booking-modal"
                            class="button booking__button">
                        View Other Options
                    </button>
                </div>
                <div id="map">
                </div>
            </div>
        </div>
    </div>
</section>

BestTourPlan/Views/Shared/MetaPartial.cshtml
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="shortcut icon" href="~/img/favicon.ico" type="image/x-icon">
<link rel="icon" href="~/img/favicon.ico" type="image/x-icon">
<link rel="preload" as="font"
      href="https://fonts.googleapis.com/css2?family=Mulish:wght@400;700&family=Nunito+Sans:wght@400;700;800&display=swap">
@if (ViewBag.Title != null)
{
    <title>@ViewBag.Title</title>
}
else
{
    <title>Best Tour Plan - Hotel Booking</title>
}

BestTourPlan/Views/Shared/ModalPartial.cshtml
<div class="modal" id="booking-modal">
    <div class="modal__overlay">
    </div>
    <div class="modal__dialog">
        <a href="#" class="modal__close">
            <img src="~/img/close.svg" alt="Icon: close">
        </a>
        <h3 class="modal__title modal__title--form">Booking</h3>
        <form class="modal__form form"
              method="post">
            <div class="modal__input-group">
                <input type="text"
                       class="input modal__input"
                       placeholder="Your Full Name*"
                       name="name"
                       required
                       minlength="2">
            </div>
            <div class="modal__input-group">
                <input type="tel"
                       class="input modal__input"
                       placeholder="Phone Number*"
                       name="phone"
                       required
                       data-mask="+7(000)-000-00-00">
            </div>
            <div class="modal__input-group">
                <input type="email"
                       class="input modal__input"
                       placeholder="Email*"
                       name="email"
                       required>
            </div>
            <textarea class="message modal__message"
                      placeholder="Message"
                      name="message"></textarea>
            <button type="submit"
                    class="button modal__button">
                Send
            </button>
            <span class="modal__info--top">*&nbsp;Required fields</span>
            <span class="modal__info--span">*&nbsp;Required fields</span>
        </form>
    </div>
</div>

BestTourPlan/Views/Shared/NewsletterPartial.cshtml
<section class="newsletter">
    <div class="newsletter-wrapper">
        <h2 class="newsletter-title__small"
            data-aos="fade-up"
            data-aos-duration="250"
            data-aos-easing="ease">
            subscribe to our
            <span class="newsletter-title__strong">Newsletter</span>
        </h2>
        <form action="send.php"
              method="POST"
              class="subscribe newsletter__subscribe form"
              data-aos="fade-up"
              data-aos-duration="300"
              data-aos-easing="ease">
            <input type="email"
                   class="input subscribe__input"
                   placeholder="Your email address"
                   name="email"
                   required />
            <button class="subscribe__button">Send</button>
        </form>
    </div>
</section>

BestTourPlan/Views/Shared/ScriptsPartial.cshtml
<script src="~/js/jquery-3.5.1.min.js" defer></script>
<script src="~/js/jquery.validate.min.js" defer></script>
<script src="~/js/jquery.mask.min.js" defer></script>
<script src="~/js/aos.js" defer></script>
<script src="~/js/swiper-bundle.min.js" defer></script>
<script src="~/js/main.js" defer></script>
@*<script src="~/js/scripts.min.js" asp-append-version="true"></script>*@

BestTourPlan/Views/Shared/StylesPartial.cshtml
<link rel="stylesheet" href="~/css/swiper-bundle.min.css" asp-append-version="true">
<link rel="stylesheet" href="~/css/aos.css" asp-append-version="true">
<link rel="stylesheet" href="~/css/style.css" asp-append-version="true">